version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loanpro
    ports:
      - "5432:5432"

  backend:
    command: cd ../api && gradle bootJar
    build: ../api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ../api:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

